version: "2"
services:
  postgres:
    image: library/postgres:latest
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root --db-name manga-reader"]
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
  manga-reader:
    build: ./src
    container_name: manga-reader
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: always
  manga-reader-test:
    build: .
    container_name: manga-reader-test
    restart: always