name: Ktor server testing CI

on:
  push:
    branches: [ $default-branch, main ]
  pull_request:
    branches: [ $default-branch, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server-jvm

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Fix ./gradlew problems
        run: chmod +x gradlew

      - name: Test with gradle
        run: ./gradlew test
